apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-main
  namespace: main
spec:
  instances: 3 
  imageName: ghcr.io/cloudnative-pg/postgresql:18

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio-store # <== REPLACE WITH THE NAME OF YOUR OBJECT STORE RESSOURCE

  storage:
    size: 1Gi

  postgresql:
    synchronous:
      method: first
      number: 2 
      standbyNamesPre:
        - pg-dr
    parameters:
      wal_log_hints: "on"      # required for clean resync (pg_rewind) on failback

  replica:
    primary: pg-main         # == own name  -> this is the global primary
    source: pg-dr              # where it streams FROM once demoted

  externalClusters:
    - name: pg-main
      connectionParameters:
        host: pg-main-rw.main.svc
        user: streaming_replica
        sslmode: verify-full
        dbname: postgres
      sslKey:
        name: pg-main-replication
        key: tls.key
      sslCert:
        name: pg-main-replication
        key: tls.crt
      sslRootCert:
        name: pg-main-ca
        key: ca.crt
    - name: pg-dr
      connectionParameters:
        host: pg-dr-rw.dr.svc
        user: streaming_replica
        sslmode: verify-full
        dbname: postgres
      sslKey:
        name: pg-dr-replication
        key: tls.key
      sslCert:
        name: pg-dr-replication
        key: tls.crt
      sslRootCert:
        name: pg-dr-ca
        key: ca.crt
