{
 "title": "CloudNativePG Query Stats",
 "tags": [ "cnpg" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "k8s_cluster", "label": "K8s Cluster", "query": { "query": "cnpg_collector_up" } },
   {
    "name": "namespace",
    "label": "Database Namespace",
    "query": {
     "query": "cnpg_collector_up{k8s_cluster=~\"$k8s_cluster\"}"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "cnpg_collector_up{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Top by Total Time",
   "type": "table",
   "description": "Statements consuming the most total execution time (excludes cnpg_metrics_exporter's own monitoring queries)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_time_calls{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_time_total_exec_time{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_time_mean_exec_time{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_time_stddev_exec_time{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_time_rows{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_time_hit_ratio{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_time_shared_blks_hit{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_time_shared_blks_read{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_time_shared_blks_dirtied{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_time_shared_blks_written{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_time_temp_blks_read{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_time_temp_blks_written{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_time_wal_bytes{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top by Call Frequency",
   "type": "table",
   "description": "Statements executed most often",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_calls_calls{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_calls_total_exec_time{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_calls_mean_exec_time{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_calls_stddev_exec_time{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_calls_rows{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_calls_hit_ratio{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_calls_shared_blks_hit{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_calls_shared_blks_read{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_calls_shared_blks_dirtied{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_calls_shared_blks_written{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_calls_temp_blks_read{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_calls_temp_blks_written{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_calls_wal_bytes{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slowest per Call",
   "type": "table",
   "description": "Statements with the highest mean execution time per call",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_avg_calls{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_avg_total_exec_time{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_avg_mean_exec_time{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_avg_stddev_exec_time{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_avg_rows{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_avg_hit_ratio{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_avg_shared_blks_hit{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_avg_shared_blks_read{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_avg_shared_blks_dirtied{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_avg_shared_blks_written{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_avg_temp_blks_read{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_avg_temp_blks_written{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_avg_wal_bytes{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heaviest Physical Reads",
   "type": "table",
   "description": "Statements reading the most shared buffer blocks from disk",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_reads_calls{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_reads_total_exec_time{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_reads_mean_exec_time{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_reads_stddev_exec_time{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_reads_rows{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_reads_hit_ratio{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_reads_shared_blks_hit{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_reads_shared_blks_read{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_reads_shared_blks_dirtied{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_reads_shared_blks_written{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_reads_temp_blks_read{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_reads_temp_blks_written{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_reads_wal_bytes{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worst Buffer Hit Ratio",
   "type": "table",
   "description": "Statements with the lowest cache hit ratio (excludes statements with zero shared-block activity)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_worst_hitratio_calls{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_worst_hitratio_total_exec_time{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_worst_hitratio_mean_exec_time{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_worst_hitratio_stddev_exec_time{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_worst_hitratio_rows{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_worst_hitratio_hit_ratio{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_worst_hitratio_shared_blks_hit{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_worst_hitratio_shared_blks_read{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_worst_hitratio_shared_blks_dirtied{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_worst_hitratio_shared_blks_written{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_worst_hitratio_temp_blks_read{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_worst_hitratio_temp_blks_written{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_worst_hitratio_wal_bytes{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heaviest Disk Spill (Temp Blocks)",
   "type": "table",
   "description": "Statements spilling the most work to temp files -- sort/hash operations exceeding work_mem. Ranked by temp_blks_read + temp_blks_written combined, matching the underlying query's ORDER BY.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_temp_calls{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_temp_total_exec_time{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_temp_mean_exec_time{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_temp_stddev_exec_time{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_temp_rows{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_temp_hit_ratio{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_temp_shared_blks_hit{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_temp_shared_blks_read{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_temp_shared_blks_dirtied{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_temp_shared_blks_written{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_temp_temp_blks_read{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_temp_temp_blks_written{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_temp_wal_bytes{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heaviest WAL Generation",
   "type": "table",
   "description": "Statements generating the most WAL -- relevant for replication/backup load",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_wal_calls{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_wal_total_exec_time{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_wal_mean_exec_time{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_wal_stddev_exec_time{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_wal_rows{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_wal_hit_ratio{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_wal_shared_blks_hit{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_wal_shared_blks_read{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_wal_shared_blks_dirtied{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_wal_shared_blks_written{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_wal_temp_blks_read{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_wal_temp_blks_written{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (queryid, datname, usename, query) (cnpg_pg_stat_statements_top_wal_wal_bytes{k8s_cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}