apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200" # Change to your Vault service URL
      path: "kv"       # Points to your KV mount path
      version: "v2"    # Tells ESO to auto-inject the "/data/" segment
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "eso" # Matches the Role you created in the Vault
          serviceAccountRef:
            name: "external-secrets" # This service account is automatically created when installing ESO
            namespace: "external-secrets"
