apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
  namespace: dev
spec:
  instances: 3

  postgresql:
    pg_hba:
      # 1. Require mTLS (cert auth) for app-user on the 'app' database
      - hostssl all app-user all cert
      # 2. Require password (scram-sha-256) for human-user on the 'app' database
      - hostssl all human-user all scram-sha-256

  # 1. Use the ESO-managed admin user/password from Vault
  bootstrap:
    initdb:
      database: admindb           # Initial database name
      owner: admin                # Set 'admin' as DB owner
      secret:
        name: cnpg-dev-admin

  # 2. Wire up cert-manager TLS certificates
  certificates:
    serverTLSSecret: pg-cluster-server-tls
    serverCASecret: pg-cluster-server-tls
    clientCASecret: pg-cluster-replication-tls
    replicationTLSSecret: pg-cluster-replication-tls

  storage:
    size: 1Gi