apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: human-user-es
  namespace: dev
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: human-user
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true" # Apply a rotated password immediately
  data:
    - secretKey: password
      remoteRef:
        key: cnpg/dev/human-user
        property: password
    - secretKey: username
      remoteRef:
        key: cnpg/dev/human-user
        property: username